apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: homelab-postgres
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-standard-trixie

  bootstrap:
    initdb:
      database: linkding
      owner: linkding
      dataChecksums: true
      secret:
        name: homelab-postgres-linkding

  managed:
    roles:
      - name: linkding
        login: true
        superuser: false
        createdb: false
        createrole: false
        passwordSecret:
          name: homelab-postgres-linkding
      - name: mealie
        ensure: present
        login: true
        superuser: false
        createdb: false
        createrole: false
        passwordSecret:
          name: homelab-postgres-mealie

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
    nodeSelector:
      node-role.kubernetes.io/control-plane: "true"

  postgresql:
    synchronous:
      method: any
      number: 1
      dataDurability: required
      failoverQuorum: true

  storage:
    storageClass: local-path
    size: 5Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 1Gi

  monitoring:
    enablePodMonitor: true
