apiVersion: v1
kind: Service
metadata:
  name: devpod
  namespace: devpod
  labels:
    app.kubernetes.io/name: devpod
    app.kubernetes.io/part-of: homelab-dev
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: devpod
  ports:
    - name: ssh
      port: 2222
      targetPort: ssh
