apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-library
  namespace: audiobookshelf
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
