apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - skynet-wrk-01
                      - skynet-wrk-02
                      - skynet-wrk-03
      securityContext:
        fsGroup: 33 # www-data group ID
        runAsUser: 33 # www-data user ID
        runAsGroup: 33 # www-data group ID

      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf@sha256:180acad33d69c99ed208676465d8edcb268fa46967735579a7810859885b1a8e
          ports:
            - containerPort: 13378
          securityContext:
            allowPrivilegeEscalation: false
          envFrom:
            - configMapRef:
                name: audiobookshelf-configmap
          volumeMounts:
            - name: app-data
              mountPath: /config
              subPath: config
            - name: app-data
              mountPath: /metadata
              subPath: metadata
            - name: library
              mountPath: /audiobooks
              subPath: audiobooks
            - name: library
              mountPath: /podcasts
              subPath: podcasts
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: audiobookshelf-data-longhorn
        - name: library
          persistentVolumeClaim:
            claimName: audiobookshelf-library-smb
