apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-data-longhorn
  namespace: audiobookshelf
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
