apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-library-smb
  namespace: audiobookshelf
spec:
  storageClassName: smb
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
