apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service.yaml
  - audiobookshelf-deployment.yaml
  - audiobookshelf-pvc-data.yaml
  - audiobookshelf-pvc-library.yaml
