apiVersion: v1
data:
  KEY: ENC[AES256_GCM,data:ELqzzp/pqvjuCjIbG2ek446w9/rP7Pgl4iU7ItTROI6Ex06fxuh+fwvY9XZoNId2hL/W306t0YvGJbiAkA3Z2EHqKPEpg6WDihkP2NggPVnWEnUYUNoPmIiRU2o=,iv:A+xMUEoLuTMDVuzID8fsiPkGkFhgYyT8qw/gfnyEZK4=,tag:xW+m2S4EqWv4xNC34U9sRA==,type:str]
  URL: ENC[AES256_GCM,data:zyrrVj6Q9hhmA5qX9J+iPsLp4u3BMVbF76Zw7wre/cPq74OmSkSOSpLbha3QWR8fznxfphbA0XK4gLEibt1o8b41FlsFi0PAMx/nvK0UeDqFoTNsddiWLRz41GGhqDfifooujbCb43rjtYoj,iv:fxq6w8XI0fY5eaCo/sgGVSXtfKsEBU1Bg5VXZdZZuuE=,tag:oSH0PPIBRqYnaCF/DQuBcQ==,type:str]
kind: Secret
type: Opaque
metadata:
  name: secret-webhook-email-triage
  namespace: kjobs
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISUtBanFsU3h5aUZzc0pS
        ZXh5Q1BKMTVrTStTY0lUcUs4OHhvQXRjaTBjCm5Ya0tKdzdsaDhHek4zYXlqbklV
        UUFNMzZRUGlSb3ZzS0pOSlpaczhLU2MKLS0tIG1MUXg5NEVVWkl0c2N3Z05CY2Ix
        cjA3V2FIVkdwTHhkZGtXcFNVdGNNVUUKQCkajwiXMJ4CkyjvwPRpF5bva62zN0e/
        dpsO+PE9waAo2YFe55gNUKtt79vC9g37ZpTYOaHO3KhH2n4eSY21rA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1as6g9mhpwx4e6dxq3fwyeqg765ap2rz43wj82qpygvwn9e2c4vasw2f3q3
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-18T04:15:45Z"
  mac: ENC[AES256_GCM,data:T4Ss7Imq8x2vOCgPl0HEjuB9KTgjsM6Yo7+v0pmwn7SjDXYzOS18gZhpDsphFR2qkG9ZiF3yZpEkhL5NO/BRHksJ5mqWPgi4qqbU5Ffo/wM3mwumyfv/H5jdLdMrpW8QVauwYDjLYiL/jGDYSS+FRSqvmmtvg2MeqUFuMOpqvDQ=,iv:JCN5kFSOjBJ2dHXXRoF3raNzpUgP+/VieXm+iGkSG4I=,tag:mWqymq5wKICGWC7wI9JZHw==,type:str]
  version: 3.13.3
