apiVersion: v1
kind: Secret
metadata:
    name: secret-webhook-email-triage
type: Opaque
data:
    KEY: ENC[AES256_GCM,data:mUCuYhCOKgm63fBx3sCRGKEBRhePKUF3zsWMCU3IQnXvq5yaTCDqYDtaW8T5lSIxxiQxAaHUqMgC5/AqBEgM5U38j7pi,iv:8BmlDYSn3CmIvksQ7wg4EXnHucJmn5HA3PDeZF1sEc8=,tag:uArGXJRGLSfkMa5qMsUIRA==,type:str]
    URL: ENC[AES256_GCM,data:FIseOCT0+QLmnLSFhzO7kt1aYsp7LsxLhkiJBGsJk2m98dMcwJ8/HL3pJtyXtso3dXr6HSKNU7avX9G9RJWyBoMUHaQkmnwr12HJUAi/TA==,iv:Dg/UNJHsz78Dv2d/7LWLMVshgi8YFVjmvqjXnE5zcQQ=,tag:HUjgAHFH92Vl3VGfQ893hw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZUV3dWlrN01ocmZ2R1l2
            V1Jwc1Y5N20wYW05NEljZm03ZVJjZlBxNEE4ClFWaWU5NW8zNjdwZ1J4aUtPanhv
            QlpSM3kxei9JL0RlaCt5TWp1bTdDcDgKLS0tIE9EK3NUSzhXVVlQUTFWRk45U2hY
            YXlhQWJsbyticzBtZUF0VjVZSWhJKzAKAvteDFNLb4+Eq1MODJtRv0+N3nbTyKgr
            xq9VNmnBgqOzzflUajatO2uJnwIiH6y7chXS7N+cb8tV8959gz3oCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1as6g9mhpwx4e6dxq3fwyeqg765ap2rz43wj82qpygvwn9e2c4vasw2f3q3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T03:57:42Z"
    mac: ENC[AES256_GCM,data:KwZiveE8leHfgImL/ilrvwKu4etuCa5yNgohso3LhmQIb+sWQFoGzAEH/uVtbKeWU6muA9cs/GDbiqnZkMXxpPt9Jc8CqJlmYTIBdjmiIT3QcaHvm5ByG0qOyY0QsSKqDS49YPORl5pYyX6J678f6gYp73SInffKHP5SAsx+lLE=,iv:ArCgqLyNdWgX6vYpcqz9XLggsfIj78sKpAnxw+HpWzI=,tag:YCaCxt2+O5gAdmR3LqbOow==,type:str]
    version: 3.13.3
