apiVersion: v1
stringData:
    KEY: ENC[AES256_GCM,data:SN9FPrWH6qtvvb6kaQ8yQQMz3ciOW8Rm9HfrPIi4NfsQ70huOC48n72nclVy3T82eyunYhqF6U8Hk01d0wLQpWek2PvK,iv:MFKDvLQ0bOKxapjGp5GnbtB3Z7dCI5YCf/dsrEHy0qU=,tag:nfO0ogx0FWdJVev94hMKBA==,type:str]
    URL: ENC[AES256_GCM,data:Cva56RO43XQfqlkssW9qDDXIUdWbX7XYYvRmZvymu73pM0kX4RgZoUTuSpeGHV/PR8KDGPrZtIsMahkOH/5vYBw6zjveZ7ubOaMiF1WhMQ==,iv:lZzUTUWZq1RCUjXUkAg9FwKIJaMUhELJOPUM7K73CLQ=,tag:Z6cU4EZpOgvcmRG6cJEaUw==,type:str]
kind: Secret
type: Opaque
metadata:
    name: secret-webhook-email-triage
    namespace: kjobs
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYzduTlVUNDRQQ3MyQjJh
            NEg4elcvcDhZUzBjc0ZtdXdRRFpGczR0UFNFClRrMHBRak92dEI3ZDFFdnJSM1Ns
            d1d2TFAyWlU1akZwa1NsZ2VUVG9rTkEKLS0tIG5EN0VRT3lOMzg3ZHRmZ1pBb0R5
            aExYQkRpZWZnQkpZcno5Z0NwdFRLMDgK/vUjvTnbIlqfDgeJcfuUeZ4I117tuJDn
            +7pI22XdvTTwlNYh0eIXGDGTT5lXkiYQtIdiPqjlstT3tU7STVxiMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1as6g9mhpwx4e6dxq3fwyeqg765ap2rz43wj82qpygvwn9e2c4vasw2f3q3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T04:57:06Z"
    mac: ENC[AES256_GCM,data:YcmDecWgtFmEYI81B80OACI/wi5OtfAKhcDUHw/64gtKO8WoyCb1FNk5rikjwzx9t2wjuaJ7YND1BVui6jgm/z9QccFNhG4kkJrg0RQZQZlZY3CXW++fFYoxKjbUk2PXv8r4z/7GvFJoxyH2C+xRZzvrGahIcJZDFbTJjjA1MYA=,iv:U2UZtfK3RewrXJEJioqxpAVgax1X1M8S4jxOjO6JwFQ=,tag:pdeteph4SLvmB37kSVHY9A==,type:str]
    version: 3.13.3
