apiVersion: v1
kind: Secret
metadata:
    name: secret-webhook-email-triage
type: secret
data:
    KEY: ENC[AES256_GCM,data:UjQq9AS3KmAQ6/yQ2UvpnelkkZgIclDUkCxUG+3L7HiGfTjzUWLvxbMD2cIWPMUcinlSbRKBGM42Ipwm9kO1dSTlI5Bt,iv:L9smjLJwRK7qpOKUNJLa7bnia729dZ0UswZ78M2fF9M=,tag:8eOIFLCoNFafgLduo7tAqQ==,type:str]
    URL: ENC[AES256_GCM,data:0qa25/SeB7OS4wpqR3bDRB3m3Xm5MlWlm41p5Ngeg1NWfyNBrsqspoYfyGkuXB+Tz53k+an2P2J/7Yh60byiD07p9kZWF6nHBsbKqdkDGg==,iv:oL+29h61jiCrH067yRuH6QUAFDCck3xpKoNuG0MZivk=,tag:dQrRSGk5mgS85rv6ZmZoRw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmQzVKajdDNWJPeGhyekdw
            TzVFWXFTSnZiT2VQQnVRMmRlSExCaDk4bXhZCmp0SnNQeVVObU1EQkk2YkdVa1Ir
            K1hWeTJ2cUpaSnZiTHluTUJWTnZUcVkKLS0tIGEvODlIRzhCZU9nQ3NFMEIxVGYz
            bnNucG9KYng0NjllbitzS2JZcUk0cEUKqviIcnNbaydZJn0JcDWXd6FEgeU0wAVh
            dBt/vvERi/HEvdIpfs6ydE69GBEQp7vp5DyxaVKghNWJryDn3HyrUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1as6g9mhpwx4e6dxq3fwyeqg765ap2rz43wj82qpygvwn9e2c4vasw2f3q3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T02:55:08Z"
    mac: ENC[AES256_GCM,data:C6ibEok1cZyYTqotK3XLGhkCDsLLL0K2YCtJt3LJy4aMBseX3WUhbKm5C86Jq3nTh1Jdkpb8RcN0gtsp0rsJhBg6hlbrVkXnDAOpZhdNc0SeL7bZGC139isHPBt4UDtrMSize4qMJvWhelK9kzQCrzWbtHkYF80XJg2w5SEx8WY=,iv:F4Jjkp0ChEO04oXnkUeEcStuurHDiVUc7tzvzSPYiAM=,tag:t2nlIWXbhwxNNF2wB33aBQ==,type:str]
    version: 3.13.3
