apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:dSqInpdV65Txy8+ZG84KmzMfm2Z2hMe6Hgb3Xpw0cigPpTOuzsxxO/p1wW5Iqw000kzyHKYTrrlR+uMSVN364iHPF6Rl5zHyYwx8O1eDrXm7a9FEd8El3K0W9olvOhWgXcB9anLvvWO05SWPKdZt7DzCc48VXxYotm5rK4t1qmgGyY+rV1bXiwUhcG5/QSzSs0TiZLarqpccvFIys0XnK4Qk0uosXjyGFewkWlEJIW59oqvZ1HCzS6y8bVBFToWBo4Ff0dZg8+gMHgMCnJGYNZhsgZINn61HvIJuZqqC7p4uiPQM7SKOazPEkHw=,iv:qExU8Hq0FlcWMSToiN1RWkJY1QtG7ad+LB4EsUWDI2w=,tag:xxV4eqr0KAqU5wcKgs0HjA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPeUFFTHV2UEJkK3dyQjdt
            YUM4NnVmTzlDdFhkNGlydC9leW95RlpITENJCjJESGpZTjZwdnZkNS96VGJzT2Yz
            bzAwUWhidGFQNjlLQ2t0SElCSDR5L0UKLS0tIGE2RmYwUWFpMUx0aFhLdzZWMmxQ
            QmxvLzZyeE9QbzRrNWx4WDRQTXRJbHcKZLp4hror6Y9K0jSxfW+IPVFTIWPPctvO
            eD8yDW09nxWzGxr5wneqMNCAIAVVBkq8x2CVAZhEuFAzIu5EDgc4yw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1as6g9mhpwx4e6dxq3fwyeqg765ap2rz43wj82qpygvwn9e2c4vasw2f3q3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T00:28:29Z"
    mac: ENC[AES256_GCM,data:YONen22uFh8pn6qymSkxAJBbmgOCOHnoaMXislIAra3qAyKY8qWa5Vj5DZ17HlFwEnrwh6bGn+Ip1qeza7+r6N+1TRuKg9M75HyzuEf9SBHpjX7y4gdY8diydp5f2jag2ISTwFRvUFV1xhHqLJA8hRC4sszADXjUvelTyr0KBnY=,iv:oV3r0I3CQ1LFv06AMkg7cVCHzn7ia6CKEAF4g0Eh/Co=,tag:JOIxPugHIHM/L1bl9oVQOg==,type:str]
    version: 3.13.3
