apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:OxHJULgwx6w=,iv:5v878YTGdG9UHskCo3rKUhRjUq8Zvr/ro1CEOh6g1Uk=,tag:OeQi/IrhGJVdDTV2F6E0Iw==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:h9PmcQm9AnINANJPGKSwsw==,iv:0P/a/u35NtYYI2HDAQNRTXpyZ2+RSStEX+XvzZIVIEI=,tag:S643IhAz4Je8vxbn0y+bAA==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcDl6bzdsSjhjVGlYZm5G
            NkZnYlZFMEJFRkJpMzJLZTA3SzdCSDdwODFJCm1IT0ljZjF0YlRqNXVuTDkzajlZ
            Z3dScnl0ek4xcDJjdTBGcS9HNVNVejgKLS0tIC9lRHZ4S3czSDhOTldoa2hvWGJ5
            OVhEbHAvMzlZaDFKTVBRSnlxWUlxLzQK+RgCZw802pS2cYcVUW1FN33giE9eTklA
            XK22DCwZzv5POfcQFVYgFLYoLFB14mjWi8Wy+dX8+xijl4XXI1FFdg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1as6g9mhpwx4e6dxq3fwyeqg765ap2rz43wj82qpygvwn9e2c4vasw2f3q3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T01:39:38Z"
    mac: ENC[AES256_GCM,data:NdwRk4ihs9oHz4uy4Y0vhyHwg2KPruhTEqaDe1qeOCdl2PRGmgSLFslz0pFl5RZ4H+7tIyYgLO+TeJjEDrUqKRWNWBmbjHCXVAwAB+Q5iw96mZq2sbiuVAKgFWXYnzzIqSis7emBFxcvHoMRYEPX64o+S8+yoBVbV1OQ/1l3mMs=,iv:MtLbZ9/gNS0FngAsa10284A8LPHcuz5WNjpHSq13MCU=,tag:qHjmNj2U6JM4LoPiv9Sofw==,type:str]
    version: 3.13.3
