apiVersion: v1
kind: Secret
metadata:
    name: linkding-database
    namespace: linkding
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:/KALSuX81EQ+/R7j,iv:4FsrjxomHS28iIAGiQTijyi0KPQ3RM4YVfTPaPTKLhQ=,tag:4xW8PKXfUxfID9NMa/+/EA==,type:str]
    password: ENC[AES256_GCM,data:zO+VpENd93MUHQgFEAA2vyl1LVePI1rvs8TXhna8VpWcOYnWVWB+9Fw70u27UcwRHqkhouC6L9MBqR5BKk/BETEFuwhVTIQERs+UfUI/yNmi/d12Vc2uRg==,iv:sqvBeDFT8jBvWdSMEWCGvtNHunZsxICy839GIChRPgQ=,tag:jfJUcwtsvJvWD5F0SDooVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMOFZDUHpUWEh1UWVkdTVl
            R3RHTE5WaFh6WVRrRjdHUGhXZnBFZ1J2L1JvCjRSSm5pd1lHZWRNOHkzeVpuN2pE
            Z2NkVmFvOUZpUSs1cURPUm5aV21mYncKLS0tIGNuTGZjMGp5aXRVRFJIcTRGYWI5
            MFdaNGNMVXdEZmhIRzZJQ3hIaFdNb0kKy1xpagDwEnEOJKDG3LakKWB12sVk3PeC
            N3YuH6c7J19Yo0h/kFm1ONb309+ep+o+jBUODpT2Q+lEWUqnZoEjKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1as6g9mhpwx4e6dxq3fwyeqg765ap2rz43wj82qpygvwn9e2c4vasw2f3q3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T13:56:02Z"
    mac: ENC[AES256_GCM,data:Gxpsve7n0u17wtjhQSXB6LDEKdZp+gdAwQDPiPN/l4nlF40FmZArngpjYXb/p1XFiSVYw5+fprAxar60Mf3jdSEGhuWEE7g46WHUsPV7S5mLHU0AC0uiRUPWnrtnmxn7yfVOr3Y9mYRFz9QiSdy8PV6VM+Akk2cHo4nb2wYqZ/o=,iv:cjPxtcpbTPVrUaGI+kj7BqLy3tW3eZR9EyaZfRPdNqs=,tag:vTJFKTt2exno6CZgiN0J3A==,type:str]
    version: 3.13.3
