apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:sxbWzOMzN+0=,iv:9tghL1ipEeGYaQkHnrhVRVQULvbjawavT1+q7aes/2c=,tag:Dw9fiyg5aQOXT0Zp10O0Vw==,type:str]
    LDSUPERUSER_PASSWORD: ENC[AES256_GCM,data:XiNNkBYH6x8y2CZH6I2tVA==,iv:ZUQFfEXlTY+enQwkqiTamyRbm8jjUo1vjQuC1+SWF+A=,tag:lwz4ehw9yBey1yHsPIkfXg==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dnRnVVlCVGhmSzhBcGlt
            bjN1cjlnNzUxM3VZOGJ6OENFcThwYWtadHgwClpoOW91QWlHaEExZDl2WFlHbXZO
            Q0VSUDBGTisxVldvaW9vNlZodWVvSkkKLS0tIFFzZGh4VkFvSWpDOHRJVEhVam5P
            SHVTQXVQWWYvQkNrZVJac3h6cmNvM0kKtKCEOkk7CN7ydNzrsk40JqTyWjTvdZ71
            0/cT/1rFZOcyPEiXzX843NWpZB9Dl3LADAJ3GiHZrAU3IR/Nio+DmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1as6g9mhpwx4e6dxq3fwyeqg765ap2rz43wj82qpygvwn9e2c4vasw2f3q3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T00:38:29Z"
    mac: ENC[AES256_GCM,data:PpfecL59/cfeNha8EOjH2cGfLRU0r1ntgtqWuKUQhTxwcSC8xgl7TX1Az23VYsSrDwgz4GEngbIR2RxdsoDYJQnMm34M5h5iTUNBxJLbhI9cvWqlLPoHbpyN2fY3596jLSyUxDf0K+NgfSj+Oa8lWg1UAyv52AKr9iOQkG99A1o=,iv:U8/079h7gIYkYDun5dqYzqiqeKs2L9ASZmcj40qSSFU=,tag:DvPYWgk2jqqZlV1Wlws7CA==,type:str]
    version: 3.13.3
