apiVersion: v1
data:
    password: ENC[AES256_GCM,data:hWvBWqQ4HFmZIDcM3//zCA==,iv:1SJLNxqgJN8cazIKDq+EwYr9Ihp8oVZpSFfLVav0Bq4=,tag:UslCLXC2VyqR2XkrAioSJQ==,type:str]
    username: ENC[AES256_GCM,data:CYBE3tfpwp7AZJCT,iv:ETQB+7zOFej0h2L3zs5ylrKVMv91o+EwYc72w2W9jqo=,tag:3lEqq65PesqTZO/N9fa6BA==,type:str]
kind: Secret
metadata:
    name: smb-credentials
    namespace: linkding
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByb0NVVTlITzhpc3J3NTE3
            bDJpVHVtemxWd1Bhem5qK1pRdEp2NERnYjA4Ck5BUzhFWmZFM0Jjd3luY2JabUpM
            eVNVbkxTREQ0SFAzYXozeTJkWkV6eFEKLS0tIGh1Y3B3cFRhaUFDZXNtbUJKZXox
            eUd4QmxWYlhoR1BJeFpyNkxXVlJ4d3cKHMC8f8vvv86CdQT79oPWpxdYPpTvWoDf
            FAr62bh91YvXvqI0ApUzcjBjaivQFhU96ZOd8CnH2QlLmCb1yf6rIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1as6g9mhpwx4e6dxq3fwyeqg765ap2rz43wj82qpygvwn9e2c4vasw2f3q3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-03T22:11:38Z"
    mac: ENC[AES256_GCM,data:J4m/hXzjrsxTtqV0lXQZmxlXZhy0w+FrZzRalpe6TGQiKr0CwbkkKyLdrSet20VDy83xRfbGfipM1ht8xhd+rnuFRWwtkjoEXpg3Nk4hNwyOLFdQyNz5z5Sdx1ZJ8FhRw3l5RkUqEGTblqHKgr/envEhgLaMUgd5WUP+OhzEdr0=,iv:4sN03iB7c3oEOAOToUco9650T4up6O9JuL8okbQ0iKE=,tag:CGBCAGl4qizR//b6Hz51jw==,type:str]
    version: 3.13.3
