apiVersion: v1
data:
    password: amFtZXM=
    user: YWRtaW4=
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4NlhKbW0zd0d1VnhUYkY2
            RkEzRE1OYTZFVVROcUJvSWRiS0hyWXd6Nm5rCkZRQi8xWUk2MU1IOGhkU3cwUmhZ
            TUxLMDU1SlZPdkhFcjlONjFkUXpyUEkKLS0tIHVaaFlVUThrRFQ0bDlRUXdLd2FC
            ZC8yUVJxRnhyazI1eXNYWE80WVhsWkkKzfnxmig6gvGFjfsX9E21Gmz/fLzopSMI
            Mn0/KBmNexP70IkMdskHjmUg3u2zifruO7yTXIOorFUY2tjW6+CUDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1as6g9mhpwx4e6dxq3fwyeqg765ap2rz43wj82qpygvwn9e2c4vasw2f3q3
    encrypted_regex: ^(data|stringData)S
    lastmodified: "2026-08-14T18:25:15Z"
    mac: ENC[AES256_GCM,data:QHkFTz5jqjpBNLk99i2ayrK4yqVaiGC0HRoEAotGHUJxF/BMlMBCKoikp5mvaJbUozGdzUUDmgXYBJSdQT2SzyCqSaRcyXLC8Ul7TDLTxUBOgWyPJv0fDQlS4qhqsjElVRgRZDeHhV0I69SXse/dHuoDQ8M+Uorl9I0a7GVx4iI=,iv:Ya0Uhw8YZSeLFvwhKaMeNrkDeErD/tS+nPLDRiGULho=,tag:zdIt6rX/dYVQD8pKV/WakA==,type:str]
    version: 3.13.3
