apiVersion: v1
kind: Secret
metadata:
    name: homelab-postgres-linkding
    namespace: database
type: kubernetes.io/basic-auth
data:
    username: ENC[AES256_GCM,data:OG/Fxi7pn3A0qBd9,iv:zfdQDXaMzUti+GynBS7rvhUPcIaKK8HzqY+pptPWKa0=,tag:cwv7miihtpMSSFxhnJ9aWA==,type:str]
    password: ENC[AES256_GCM,data:jJWComoCMxLOX21ltz8aCVTxJJvkPAo+gj39VHxqHHJdL1atWSnDTJab3LZd7IyW78+O71YoHUDKk5/f0bauIuttVBBqc9vfPOAhBpnHfVySHgS+dB/OIA==,iv:pqx/T8t0mWQxcoQLDzhMvbAp8q7TV+pYi5fvEODmbUU=,tag:y4mzkowO35FLonTDtlOi5w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBL2lrMEJqbWVFTWRPb09s
            b1ZZWncwb1k4dU5VQWNBYzFnWlo2d081Z3o4ClZ6ZFZObkVGQlBadXp0aWtpSGVO
            a0hGRGtJVWt5Mk9nenFCeWwrR3NwZ1UKLS0tIGh2b0EyNFBMc3VubkdUWEYreXdv
            SkpueGlaRnVjMDlkYTFPcGdqZjRodlUKhhVm17RV1hsWSAe9lWESZxi7krNfdpZ1
            lTIHmuyRjNsEqzn3GpN1QIluxexLP/wLsJf8pzkQObUQoMDBZk+F8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1as6g9mhpwx4e6dxq3fwyeqg765ap2rz43wj82qpygvwn9e2c4vasw2f3q3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T13:56:02Z"
    mac: ENC[AES256_GCM,data:7G3d4yoxE/QEXHzEaA6GKSzpBKX8KtFjtkfc1zb2+StPGXiCDQXY8MUBHZbaC+LmJSjZ14wwtszMwIKQItdM0BMjr8UTuPLf10fvj+VyX9q8RQ0Le0bRNG/GszcaiuIrohu0opsBn74aOGCCgpVgofrShdjmFb9wEEawloIzxEM=,iv:uUwxSDQJQtFyQJUrydJZuBIijHvTAdeZgUaOFIhSyGE=,tag:qlHD4tAjQ9TzvC+ZrKkgeQ==,type:str]
    version: 3.13.3
