apiVersion: v1
kind: Secret
metadata:
    name: homelab-postgres-mealie
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:H3qZeqNl,iv:VaigJNTU09tAKS7yoqVNKVMAwMiLavWnL/MT08hBxNM=,tag:ebX690OJd8Prdy8b3mPvxg==,type:str]
    password: ENC[AES256_GCM,data:BEPsgCDgrRA7oxldt54HKX2lxabB/NdhOW8yHK+IrQ==,iv:b+dg/9kBb9+p7n/FcTte5Cz+hlmSFp38kcaYGLyn+i0=,tag:wiXBq/5YPXDqWHeI18wsSg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUVF0Wm5ac2pkMm5zTExr
            bmRCN3lOeHRlMFlNZFhFMHVtMFArekRsL1FZCm9ETU9kVWFEYWYrL0hGNnhRUWtv
            ZXRqL0JMWUxnSkdMV3pud2NOMy9tczgKLS0tIHd1NWJmMnN4UkU1dk5pcnlYZVlu
            dlZwYWJvMVRFdm8ra3hrVWwvLzlvNE0K7j2HZZ7bnFnN5h28nKaO8MsihGOw0JgR
            NhRW3vJBrz5RvCdYnKdOT24YBOrOHf1eYDxICiWbYsgd7EjHJVtGdg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1as6g9mhpwx4e6dxq3fwyeqg765ap2rz43wj82qpygvwn9e2c4vasw2f3q3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T19:02:10Z"
    mac: ENC[AES256_GCM,data:6+RrARJ/4eZN7rlPG08iKGcwFFya2CDbJQMJps/1IS/J8Qveicxx/It3ASGz7X0ArL3Np1WaQx/nD4yfP1BvfFr46tyfZLVQhpmFEJdGJQT3Sr+aKBQw4G8C/12TLaYFs/+nm/cQZ53mZq3g1sVUwN+e1ayXmXPCoCbNWbA9/OQ=,iv:SbIHB6qhysH+xomwSW7lvyPzFLrk/9ihWJ9V/8dAWkQ=,tag:CoFl9E7VleG8yWfFIi0FNQ==,type:str]
    version: 3.13.3
