apiVersion: v1
kind: Secret
metadata:
    name: smb-32tb-credentials
    namespace: devpod
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:6yKXUNI=,iv:9ydCoZzlJ2TLvB6dWwU3nXB/etYm2tBT2MquUtT+Tyo=,tag:a3+Wop/5UynV3Jx11mG74Q==,type:str]
    password: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQajRYNWN5RjNFY1RFNTZr
            LzdpN05NdjFna01OdkYyNW5LU3k4Kzd4M0h3CnNobDg5VTRpR28zNXc1Z2psZ3M4
            ZEJHSTVFcEhLbng4ZzZzTFF4RFNpTEkKLS0tIGRuK2lENnYvdm11YkdUSnh2WVpY
            ajlnbi9rN0F3SE94NEJKQ0o5Q0dlU2sKgvi2CJYmlMJC7zleDdgjhz9pJ42tTGFo
            6/Uo8vugjoY1OuoXFVVtAxBp1O5J4m+ZCTqxcFF7ebxt1zWpowh5ow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1as6g9mhpwx4e6dxq3fwyeqg765ap2rz43wj82qpygvwn9e2c4vasw2f3q3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T23:49:15Z"
    mac: ENC[AES256_GCM,data:ROL/M09XQYR+0BFzfscI+c+74aTBjaqkxYEJa6oxKqBhTqLbbKIThtzf/8Hi57umKb2//OyegUeGb0/W6BpCo7T0ssVjEz8Ha+Xg3L2cFW8xVMSUCgD86zwI65dZCd3JJhkeKEgT38P55wywOlQGIHi20ZZuWc0nDwg9D4sAFSc=,iv:bKLzg6lhsG1oAIaaevUliqhKRN/toDfNRsSOu7wNfZs=,tag:b0McMluJKkYqpLbmL3rxuQ==,type:str]
    version: 3.13.3
