apiVersion: v1
kind: Secret
metadata:
    name: mealie-database
    namespace: mealie
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:bAVXFCcZ,iv:3P8P9aiLF8MXxPmf4IxpKLUFXXYvbYe7spkFzFP1wDw=,tag:AMKolCNfqiCjezzmn+HIlw==,type:str]
    password: ENC[AES256_GCM,data:i6W5aeYG4Jtbuz0pDEvANJDvOku+fPCn6lFk1CNrcQ==,iv:jd8Fim7GXZ/eCbajp37XicBfFJXilCB0Kd7IQbZ+wJA=,tag:veylksXwgE5ysXPf3Njghg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUGNTdXBoNnJ4UW5OaUtS
            amZLVXQvVTZOSkUvQiszSXcrMEp1UExTdVNRCldUMGgzbjVBa1hwaFBadkRwSUp2
            elhSYXBqcVdla2srbXBETlBrbldVWkkKLS0tIHhyQS9xb3ljRWM2THhOMW1PQlAw
            WW9sUVpHOGN3R1dQOUZ1Q3JEV2dsV1EKaafjRRtCG1T2tKv2EwwyzlLFCCgrVoPZ
            IX1B6ntApuVGHOgpTq4Neu9wzugspcuB7d14amSnsS68OGfkvlcbkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1as6g9mhpwx4e6dxq3fwyeqg765ap2rz43wj82qpygvwn9e2c4vasw2f3q3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T19:02:10Z"
    mac: ENC[AES256_GCM,data:gW3yRQNdlckHENoeDA5Yr7UuJWsEMxXaUCf95a4TUGyhCQWcsOCtS9GtME+tg4cXTXRAO9Ei2gVJLSl3Rkb5dH1Uz5ORTU3p/E0oQe0x/JiOHVsqCGF9c0PihkHKRrybjKp0+C7tj29ca3DApRLT4CNwlIrYG1h+F7HECE4hT94=,iv:tWBl6ikcHLiID5qZBJSR7LJLTTD5CzI6xrXBmWBy990=,tag:BQL0YjMmN9kxxdggBU2Jkw==,type:str]
    version: 3.13.3
