apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-tunnel
    namespace: cloudflare
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:oCsAI8ElQIbeOZe4+AGwZcKeo/lOmCRAbKURfQE6/z7+S5OYKxXlOjj2Mqog8UeHA+YP6QTuGdKIjC3KgwB+lYUuivMw83fLlhOwfbu60ky7AIw2MCLgU8wgZH49OT3sPEAGl1JwQSwIBV4c7ULhWWtkkANDbUqQ9/Qwf9dtKnFR9IaiKWhlCgc0tMkkz9EbxcR5BEoZsmzSHHUXoh/x6byR9dC15FEFjmzejFFRUN5BK+r8,iv:p4ZHMUbLc64hpdTVBQ+aAKGtvMdidAcdTgspWhLLBMo=,tag:JFwAV5U+Urt39YCEjuUPqQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UVBlcDQ1bWRKS1dqY0NE
            ZWR5ZzFWZmtUeTkxU3dweTYraVJ0WU1Ic25JCmkvdXkwUXYraUdXNlJEQlpQZFFV
            OThBSVZReVZVNUtjM2xCU1pCQUx6S3cKLS0tIDU1TUNpMDY2bVdVbE1mWGlnQU44
            MVBpeEFOWE5CZkI3RzNUVDVZNWNINU0KYIGxGh/Bt/cT61n1KccqaRTQyfT/axDN
            Mt60KXOYzsZG5VXueSfLpiKfk7B1Zx+HEhVl2JjJEOAt/EgkOBTZAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1as6g9mhpwx4e6dxq3fwyeqg765ap2rz43wj82qpygvwn9e2c4vasw2f3q3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T15:49:55Z"
    mac: ENC[AES256_GCM,data:GCDSg27oOKMXBxdPJKbN1ti1EjTRcsAi/9/8vRwEntGwzbx0YnkQo9nfjVCyscwUJoqgkdhTIi006UYo2k+dDd5KQsQbel7tQ8jruv3p+3eIxe+tfFIis12UilAI1uSymfcvI//ikcKu1dvo7IaoPPgsJsZCc+BWHyMwC7oHedg=,iv:oR/u8LaofQhxdDB17vBBX0wNnbHmM8+F19eRkuopv70=,tag:w8av7OCvViAoM1/ux3wvew==,type:str]
    version: 3.13.3
