apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:ollY4g4=,iv:6gll+EeZzeWRW0X6MX2JYNRx0eufzfBOvyS4X/jYhQQ=,tag:YH1uYyji9OJUoXKUfM3Myg==,type:str]
    admin-password: ENC[AES256_GCM,data:ACrDgiUgWIeCOpc=,iv:1aaoh1dx8RITdkOlvPFQCSLbDy4WLAoQaF4kKN5jnZo=,tag:mqyIhgRMB/LozbE8Oq/33Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMWgzQ1VIaVM0WmIzcU9I
            UGp5d3ZzaWhSR01GSnZ2d01nZVlneHZJYVJBCm9scVB1Wm5xekdWalNONHRGMnly
            RGZndGxOVDRsTVhET2xKdGNsVDZSN3cKLS0tIFVqTC9jUlR6UEY5WnlabndKTzdD
            bklsc2J2bUp1S3I0RE9VY251b3Z1ZmMKfv9KY6dWoDB6oCxbGfbRHfa2Otvk/eOl
            xbjAsT9OPjvqAIh4GKbatRy4ld5OWveXj7Riz0E0kkKpEvUy7ze5eQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1as6g9mhpwx4e6dxq3fwyeqg765ap2rz43wj82qpygvwn9e2c4vasw2f3q3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T01:17:18Z"
    mac: ENC[AES256_GCM,data:W9XbLd4XsU1CEGgotP2jtb+EhgUdE/+44wc7Iun9Dn2XyvUgl1zQDzzt2WO+fGsDinX8ZSBSxop0JsuuKY2lrPm4jqvACKgrG1UevlIMCKBbInebP347M5SvzmBzbp0nzQb8H9y5tcKaxlmS16EFLBrqlR8G7a5T1QvwoTtUDJI=,iv:yZ7NPAOVKymMEL/10XfDMxqLPOhbpdjP5fqlR2F3LnU=,tag:iEK/WlBP92RAE7ywMD+QQw==,type:str]
    version: 3.13.3
