apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:StrRUac=,iv:3aM/+kV34UOwjkOoSy2o6Wy3lOti6eVfLqLQDwiKPT8=,tag:gxSbFhpxtU6V94wjaDQ5kg==,type:str]
    admin-password: ENC[AES256_GCM,data:EoGrbip/RZp00iaxma3P1KY8CElaF348Bi9p8UJ2YdwHEhSdHNEj9FlpWto4ur9oQjYgyVze7HIpc4MZR2x00r7J1LfmzCt78EV1YA==,iv:xekAD55NDAydfWkuVUu4W4AuJtJj9uQdiNzc26ETNAU=,tag:OLQ8ZoeZcLRRl6gf5lkSvA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZklSK1V1bEZIdndvZVZ2
            Z2dBMnNTWW9ubGV5OGFib1RRZ3BrdkE3VUR3CkZPMEk3U1dmMXorTXZLaFBSbFdH
            cUZFaHFTSDV4RUV6RmZWQjV6SURjZ1EKLS0tIGZoUGVXT1JwVTNsbVRsUENaUkNC
            MVpXa0NjU20yM3NxMzdQU0NYOGdSTmsKtkbZVo+2khduOEbeMF5Q/ec1foCOEtMC
            yYQ8Z4pRZS7SnwlHhkJG96btUELKX808zBfJOa+OAxviT+gSyO6yww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1as6g9mhpwx4e6dxq3fwyeqg765ap2rz43wj82qpygvwn9e2c4vasw2f3q3
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T02:28:52Z"
    mac: ENC[AES256_GCM,data:WO+ikh4SyE4rqsXJztL+ETuNZeKN1x/lnmLBz3f+X0Ud/8O9NPHxnaAA90B9Y4SORBeVbeFBm0hlrz1Rf9IoNJ4r0EHkyhaH/b5RlNMvPUinuwS3J9MbVeGcVRaUuIWPUwJYgpv1P8tQ8jXJWPl7LIanjtFzaWqCWt84UTYwAZk=,iv:om8hcFNY1z8wNasped2AG5+WNygJaJSK9OYZO9FlEa4=,tag:Qx6Rg4IrGbCYpA4fe2KpbQ==,type:str]
    version: 3.13.3
