apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data-smb
spec:
  storageClassName: smb
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
